### ISSUE TITLE
System does not write "Umlaute" in file names and causes Email Error

### ISSUE THREAD

**Issue by kokon404** [itx-informationssysteme/jobapplications#55]
When I put ä,ö or ü in in the application form Emails are not sent and the file in fileadmin/applications will not be created.
"ITX.Jobapplications.Controller.ApplicationController": Error trying to send a mail: Path "fileadmin/applications/Name_%C3%B6...._f1c8e8563c655fbfab8fbafd995e1bca/cv_testpdf.pdf" is not readable. 
This only happens with Umlauts.

"exception":"Symfony\\Component\\Mime\\Exception\\RfcComplianceException: Email \"\" does not comply with addr-spec of RFC 2822. in /html/typo3-staging/typo3_src-10.4.21/vendor/symfony/mime/Address.php:56 [...]
ITX\\Jobapplications\\Utility\\Mail\\MailFluid->addressArrayToObject('', '') [...]

**Comment by itx-benjamin-jasper** [comment]
Hi there, I can't reproduce your issue. The filepath gets sanitized by a function provided by TYPO3, so my guess is that something in your installation isn't configured properly.
For example, are you using a UTF-8 filesystem (['TYPO3_CONF_VARS']['SYS']['UTF8filesystem'])? If so I would also check if your locale (['TYPO3_CONF_VARS']['SYS']['systemLocale']) is set correctly and available on your server. 
You could also check the environment status for issues.

**Comment by kokon404** [comment]
Hi Benjamin,
thanks for the answer.
That's all fine. Just two assets in typo3temp with unexpected server response.
by the way it also looks like that bugfix
* [BUGFIX] fixed bug where no applications would come up in backend module when no backend user contact relationship
doesn't work. I had to connect the admin user to the contact person.

**Comment by itx-benjamin-jasper** [comment]
So does this mean your issue is fixed now or where is the connection to this bugfix?

**Comment by kokon404** [comment]
No that was just what I have found out on top as I tried to find the problem. The original issue is not solved.

**Comment by itx-benjamin-jasper** [comment]
Ok, well that's too bad, I don't know how to help you as I am almost certain that it's a config issue and I can't reproduce this. 
If you want you can try to debug this on your server: the function used for this is \TYPO3\CMS\Core\Resource\Driver\LocalDriver::sanitizeFileName(). It gets called here:
https://github.com/itx-informationssysteme/jobapplications/blob/ed69158cbf900d7f09b08bdea27cddbed60163d5/Classes/Service/ApplicationFileService.php#L33

Feel free to share your results!
